name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the action
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t quelpoke .
    - name: Tag the Docker image
      run: docker tag quelpoke europe-west9-docker.pkg.dev/infal-devops-sysops/student-thibaud/quelpoke:latest
    
    - name: Docker login
      uses: docker/login-action@v3
      with:
        registry: europe-west9-docker.pkg.dev
        username: _json_key_base64
        password: ${{secrets.PUSH_KEY}}

    - name: Push the Docker image
      run: docker push europe-west9-docker.pkg.dev/infal-devops-sysops/student-thibaud/quelpoke:latest
